name: First Time Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Oops! Looks like you found a bug! Or maybe just an improvement! We'll get right on that!"
        pr-message: "Congrats on your first pull request! Thanks for contributing to Volts of Doom!"
